/**
 * ODDLY Team Name Normalizer
 *
 * Different data sources use different canonical names for the same team:
 * - La Liga: "FC Barcelona", "Real Madrid CF", "Valencia CF"
 * - Eredivisie: "feyenoord rotterdam", "afc ajax"
 * - Premier League: "brentford", "bournemouth"
 * - Upcoming fixtures: "Bayern Munich", "Barcelona", "Real Madrid"
 *
 * This module normalizes all names to a common key for lookups.
 */

// ── Alias map: variant → normalized key ──────────────────────────────────
const ALIASES: Record<string, string> = {
  // Spain
  "fc barcelona": "barcelona",
  "barcelona": "barcelona",
  "real madrid cf": "real madrid",
  "real madrid": "real madrid",
  "club atlético de madrid": "atletico madrid",
  "atletico madrid": "atletico madrid",
  "athletic club": "athletic bilbao",
  "athletic": "athletic bilbao",
  "athletic bilbao": "athletic bilbao",
  "real betis balompié": "real betis",
  "real betis": "real betis",
  "valencia cf": "valencia",
  "valencia": "valencia",
  "real sociedad de fútbol": "real sociedad",
  "real sociedad": "real sociedad",
  "villarreal cf": "villarreal",
  "villarreal": "villarreal",
  "sevilla fc": "sevilla",
  "sevilla": "sevilla",
  "ca osasuna": "osasuna",
  "osasuna": "osasuna",
  "getafe cf": "getafe",
  "getafe": "getafe",
  "girona fc": "girona",
  "girona": "girona",
  "rc celta de vigo": "celta vigo",
  "celta": "celta vigo",
  "celta vigo": "celta vigo",
  "rcd espanyol de barcelona": "espanyol",
  "espanyol": "espanyol",
  "rcd mallorca": "mallorca",
  "mallorca": "mallorca",
  "rayo vallecano de madrid": "rayo vallecano",
  "rayo vallecano": "rayo vallecano",
  "cd leganés": "leganes",
  "leganes": "leganes",
  "deportivo alavés": "alaves",
  "alaves": "alaves",
  "real valladolid cf": "valladolid",
  "valladolid": "valladolid",
  "cádiz cf": "cadiz",
  "cadiz": "cadiz",
  "ud almería": "almeria",
  "almeria": "almeria",
  "ud las palmas": "las palmas",
  "las palmas": "las palmas",
  "granada cf": "granada",
  "granada": "granada",
  "elche cf": "elche",
  "elche": "elche",
  "levante ud": "levante",
  "levante": "levante",
  "real oviedo": "oviedo",
  "oviedo": "oviedo",

  // Germany
  "fc bayern münchen": "bayern munich",
  "bayern munich": "bayern munich",
  "bayern münchen": "bayern munich",
  "borussia dortmund": "borussia dortmund",
  "dortmund": "borussia dortmund",
  "bayer 04 leverkusen": "bayer leverkusen",
  "bayer leverkusen": "bayer leverkusen",
  "rb leipzig": "rb leipzig",
  "vfb stuttgart": "stuttgart",
  "stuttgart": "stuttgart",
  "vfl wolfsburg": "wolfsburg",
  "wolfsburg": "wolfsburg",
  "sc freiburg": "freiburg",
  "freiburg": "freiburg",
  "eintracht frankfurt": "eintracht frankfurt",
  "frankfurt": "eintracht frankfurt",
  "1. fc köln": "koln",
  "1. fc union berlin": "union berlin",
  "union berlin": "union berlin",
  "borussia mönchengladbach": "monchengladbach",
  "monchengladbach": "monchengladbach",
  "tsg 1899 hoffenheim": "hoffenheim",
  "tsg hoffenheim": "hoffenheim",
  "hoffenheim": "hoffenheim",
  "1. fc heidenheim 1846": "heidenheim",
  "1. fsv mainz 05": "mainz",
  "vfl bochum 1848": "bochum",
  "sv werder bremen": "werder bremen",
  "werder bremen": "werder bremen",
  "1. fc heidenheim": "heidenheim",
  "fc augsburg": "augsburg",
  "augsburg": "augsburg",
  "sv darmstadt 98": "darmstadt",

  // England - Premier League
  "manchester city": "manchester city",
  "man city": "manchester city",
  "man utd": "manchester united",
  "man united": "manchester united",
  "manchester united": "manchester united",
  "tottenham hotspur": "tottenham",
  "tottenham": "tottenham",
  "spurs": "tottenham",
  "west ham united": "west ham",
  "west ham": "west ham",
  "newcastle united": "newcastle",
  "newcastle": "newcastle",
  "newcastle utd": "newcastle",
  "brighton & hove albion": "brighton",
  "brighton": "brighton",
  "brighton and hove albion": "brighton",
  "wolverhampton wanderers": "wolves",
  "wolves": "wolves",
  "wolverhampton": "wolves",
  "nottingham forest": "nottingham forest",
  "nottingham": "nottingham forest",
  "nottm forest": "nottingham forest",
  "afc bournemouth": "bournemouth",
  "bournemouth": "bournemouth",
  "aston villa": "aston villa",
  "villa": "aston villa",
  "crystal palace": "crystal palace",
  "palace": "crystal palace",
  "fulham": "fulham",
  "everton": "everton",
  "brentford": "brentford",
  "the bees": "brentford",
  "ipswich town": "ipswich",
  "ipswich": "ipswich",
  "leicester city": "leicester",
  "leicester": "leicester",
  "foxes": "leicester",
  "southampton": "southampton",
  "saints": "southampton",
  "liverpool": "liverpool",
  "reds": "liverpool",
  "arsenal": "arsenal",
  "gunners": "arsenal",
  "the gunners": "arsenal",
  "chelsea": "chelsea",
  "blues": "chelsea",
  // England - Championship
  "leeds united": "leeds",
  "leeds": "leeds",
  "burnley": "burnley",
  "clarets": "burnley",
  "sheffield united": "sheffield united",
  "blades": "sheffield united",
  "sheffield wednesday": "sheffield wednesday",
  "owls": "sheffield wednesday",
  "norwich city": "norwich",
  "norwich": "norwich",
  "canaries": "norwich",
  "watford": "watford",
  "hornets": "watford",
  "west bromwich albion": "west brom",
  "west brom": "west brom",
  "wba": "west brom",
  "coventry city": "coventry",
  "coventry": "coventry",
  "sky blues": "coventry",
  "hull city": "hull",
  "hull": "hull",
  "tigers": "hull",
  "middlesbrough": "middlesbrough",
  "boro": "middlesbrough",
  "portsmouth": "portsmouth",
  "pompey": "portsmouth",
  "sunderland": "sunderland",
  "black cats": "sunderland",
  "swansea city": "swansea",
  "swansea": "swansea",
  "swans": "swansea",
  "cardiff city": "cardiff",
  "cardiff": "cardiff",
  "bluebirds": "cardiff",
  "blackburn rovers": "blackburn",
  "blackburn": "blackburn",
  "rovers": "blackburn",
  "derby county": "derby",
  "derby": "derby",
  "rams": "derby",
  "preston north end": "preston",
  "preston": "preston",
  "pne": "preston",
  "queens park rangers": "qpr",
  "qpr": "qpr",
  "millwall": "millwall",
  "lions": "millwall",
  "lincoln city": "lincoln",
  "lincoln": "lincoln",
  "imps": "lincoln",
  "bolton wanderers": "bolton",
  "bolton": "bolton",
  "wanderers": "bolton",
  "bristol city": "bristol city",
  "robines": "bristol city",
  "charlton athletic": "charlton",
  "charlton": "charlton",
  "addicks": "charlton",
  "birmingham city": "birmingham",
  "birmingham": "birmingham",
  "stoke city": "stoke",
  "stoke": "stoke",
  "potters": "stoke",
  "reading": "reading",
  "royals": "reading",
  "huddersfield town": "huddersfield",
  "huddersfield": "huddersfield",
  "terriers": "huddersfield",
  "bristol rovers": "bristol rovers",
  "oxford united": "oxford united",
  "oxford": "oxford united",
  "plymouth argyle": "plymouth",
  "plymouth": "plymouth",
  "pilgrims": "plymouth",

  // Italy - Serie A
  "inter milan": "inter",
  "internazionale": "inter",
  "internazionale milano": "inter",
  "fc internazionale milano": "inter",
  "inter": "inter",
  "nerazzurri": "inter",
  "ac milan": "milan",
  "milan": "milan",
  "rossoneri": "milan",
  "ssc napoli": "napoli",
  "napoli": "napoli",
  "partenopei": "napoli",
  "as roma": "roma",
  "roma": "roma",
  "giallorossi": "roma",
  "ss lazio": "lazio",
  "lazio": "lazio",
  "biancoceleste": "lazio",
  "acf fiorentina": "fiorentina",
  "fiorentina": "fiorentina",
  "viola": "fiorentina",
  "atalanta": "atalanta",
  "atalanta bc": "atalanta",
  "la dea": "atalanta",
  "juventus": "juventus",
  "juve": "juventus",
  "fc torino": "torino",
  "torino": "torino",
  "granata": "torino",
  "genoa cfc": "genoa",
  "genoa": "genoa",
  "grifone": "genoa",
  "como 1907": "como",
  "como": "como",
  "fc lugano": "como",
  "udinese calcio": "udinese",
  "udinese": "udinese",
  "bianconeri": "udinese",
  "cagliari calcio": "cagliari",
  "cagliari": "cagliari",
  "rossoblu": "cagliari",
  "empoli fc": "empoli",
  "empoli": "empoli",
  "azzurri": "empoli",
  "parma calcio 1913": "parma",
  "parma": "parma",
  "crociati": "parma",
  "hellas verona": "verona",
  "verona": "verona",
  "gialloblu": "verona",
  "us lecce": "lecce",
  "lecce": "lecce",
  "ac monza": "monza",
  "monza": "monza",
  "biancorossi": "monza",
  "venezia fc": "venezia",
  "venezia": "venezia",
  "arancioneroverdi": "venezia",
  "us sassuolo": "sassuolo",
  "sassuolo": "sassuolo",
  "neroverdi": "sassuolo",
  "us palermo": "palermo",
  "palermo": "palermo",
  "rosanero": "palermo",
  "sampdoria": "sampdoria",
  "blucerchiati": "sampdoria",
  "brescia": "brescia",
  "leonesa": "brescia",
  "spal": "spal",
  "ferrara": "spal",
  "benevento": "benevento",
  "stregoni": "benevento",
  "frosinone": "frosinone",
  "canarini": "frosinone",

  // France - Ligue 1
  "paris saint-germain": "paris saint-germain",
  "paris saint germain": "paris saint-germain",
  "psg": "paris saint-germain",
  "paris fc": "paris fc",
  "olympique lyonnais": "lyon",
  "olympique lyon": "lyon",
  "lyon": "lyon",
  "les gones": "lyon",
  "olympique de marseille": "marseille",
  "olympique marseille": "marseille",
  "marseille": "marseille",
  "om": "marseille",
  "as monaco fc": "monaco",
  "as monaco": "monaco",
  "monaco": "monaco",
  "asm monaco": "monaco",
  "ogc nice": "nice",
  "nice": "nice",
  "les aiglons": "nice",
  "lille osc": "lille",
  "lille": "lille",
  "losc lille": "lille",
  "les dogues": "lille",
  "rc lens": "lens",
  "lens": "lens",
  "sang et or": "lens",
  "stade brestois 29": "brest",
  "stade brestois": "brest",
  "brest": "brest",
  "sb29": "brest",
  "stade rennais fc": "rennes",
  "stade rennais": "rennes",
  "rennes": "rennes",
  "les rouges et noirs": "rennes",
  "rc strasbourg alsace": "strasbourg",
  "rc strasbourg": "strasbourg",
  "strasbourg": "strasbourg",
  "rcs": "strasbourg",
  "toulouse fc": "toulouse",
  "toulouse": "toulouse",
  "le tef": "toulouse",
  "fc nantes": "nantes",
  "nantes": "nantes",
  "les canaris": "nantes",
  "stade de reims": "reims",
  "reims": "reims",
  "les remois": "reims",
  "montpellier hsc": "montpellier",
  "montpellier": "montpellier",
  "mhsc": "montpellier",
  "saint-etienne": "saint-etienne",
  "saint etienne": "saint-etienne",
  "as saint-etienne": "saint-etienne",
  "les verts": "saint-etienne",
  "auxerre": "auxerre",
  "aja": "auxerre",
  "angers sco": "angers",
  "angers": "angers",
  "le havre ac": "le havre",
  "le havre": "le havre",
  "lhac": "le havre",
  "fc lorient": "lorient",
  "lorient": "lorient",
  "les merlus": "lorient",
  "estac troyes": "troyes",
  "troyes": "troyes",
  "estac": "troyes",
  "fc metz": "metz",
  "metz": "metz",
  "les grenats": "metz",
  "clermont foot": "clermont",
  "clermont": "clermont",
  "105 clermont foot 63": "clermont",

  // Portugal
  "sl benfica": "benfica",
  "benfica": "benfica",
  "fc porto": "porto",
  "porto": "porto",
  "sporting cp": "sporting cp",
  "sporting": "sporting cp",
  "sc braga": "braga",
  "braga": "braga",
  "rio ave": "rio ave",
  "gil vicente": "gil vicente",
  "estoril praia": "estoril",
  "estoril": "estoril",
  "cd nacional": "nacional",
  "moreirense": "moreirense",
  "santa clara": "santa clara",
  "sc farense": "farense",
  "alverca": "alverca",

  // Netherlands
  "afc ajax": "ajax",
  "ajax": "ajax",
  "psv eindhoven": "psv",
  "psv": "psv",
  "feyenoord": "feyenoord",
  "feyenoord rotterdam": "feyenoord",
  "az alkmaar": "az",
  "az": "az",
  "fc utrecht": "utrecht",
  "utrecht": "utrecht",
  "fc twente": "twente",
  "fc twente '65": "twente",
  "twente": "twente",
  "sc heerenveen": "heerenveen",
  "heerenveen": "heerenveen",
  "go ahead eagles": "go ahead eagles",
  "go ahead": "go ahead eagles",
  "fc groningen": "groningen",
  "groningen": "groningen",
  "nac breda": "nac breda",
  "nec nijmegen": "nec",
  "nec": "nec",
  "sparta rotterdam": "sparta rotterdam",
  "sparta": "sparta rotterdam",
  "pec zwolle": "zwolle",
  "zwolle": "zwolle",
  "fortuna sittard": "fortuna sittard",
  "sittard": "fortuna sittard",
  "willem ii": "willem ii",
  "willem ii tilburg": "willem ii",
  "rkc waalwijk": "waalwijk",
  "waalwijk": "waalwijk",
  "heracles": "heracles",
  "excelsior": "excelsior",
  "almere city": "almere city",
  "den haag": "den haag",

  // Brazil
  "flamengo": "flamengo",
  "mirassol": "mirassol",
  "mineiro": "atletico mineiro",
  "atletico mineiro": "atletico mineiro",
  "bragantino": "bragantino",
  "são paulo": "sao paulo",
  "sao paulo": "sao paulo",
  "santos": "santos",
  "botafogo": "botafogo",
  "grêmio": "gremio",
  "gremio": "gremio",
  "chapecoense": "chapecoense",
  "vasco da gama": "vasco",
  "vasco": "vasco",
  "cruzeiro": "cruzeiro",
  "internacional": "internacional",
  "fluminense": "fluminense",
  "corinthians": "corinthians",
  "palmeiras": "palmeiras",
};

/**
 * Normalize a team name to a canonical key for lookups.
 * Strips accents, lowercases, and maps through alias table.
 */
export function normalizeTeamName(name: string): string {
  if (!name) return "";
  // Strip accents and lowercase
  const normalized = name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
  return ALIASES[normalized] || normalized;
}

/**
 * Build a lookup map from raw team names to normalized keys.
 * Use this to convert form/Elo maps built from historical data.
 */
export function buildNormalizedMap<T>(
  rawMap: Record<string, T>
): Record<string, T> {
  const result: Record<string, T> = {};
  for (const [key, value] of Object.entries(rawMap)) {
    const normalized = normalizeTeamName(key);
    result[normalized] = value;
    // Also store original for direct lookups
    result[key] = value;
  }
  return result;
}
